"""Scaffold Arena protocol-v1 public API."""

from .canonical import canonical_configuration_hash, canonical_json, sha256
from .design import expand_design, fractional_design_metadata, treatment_id
from .models import (
    AggregateBudgetSpec,
    AttemptEnvelope,
    BudgetSpec,
    DecisionBrief,
    Episode,
    EvaluationRecord,
    ExecutionProvenance,
    ExperimentSpec,
    FactorSpec,
    GraderSpec,
    HarnessSpec,
    ManipulationCheck,
    OutcomeVector,
    ProtocolReadinessReport,
    ScenarioSpec,
    StudyPack,
    TraceEvent,
    TreatmentMutation,
    assess_study_pack_readiness,
)
from .study_pack import (
    canonical_manifest,
    freeze_experiment,
    load_study_pack,
    manifest_hash,
    verify_manifest,
)

__all__ = [
    "AggregateBudgetSpec",
    "AttemptEnvelope",
    "BudgetSpec",
    "DecisionBrief",
    "Episode",
    "EvaluationRecord",
    "ExecutionProvenance",
    "ExperimentSpec",
    "FactorSpec",
    "GraderSpec",
    "HarnessSpec",
    "ManipulationCheck",
    "OutcomeVector",
    "ProtocolReadinessReport",
    "ScenarioSpec",
    "StudyPack",
    "TraceEvent",
    "TreatmentMutation",
    "assess_study_pack_readiness",
    "canonical_configuration_hash",
    "canonical_json",
    "canonical_manifest",
    "expand_design",
    "fractional_design_metadata",
    "freeze_experiment",
    "load_study_pack",
    "manifest_hash",
    "sha256",
    "treatment_id",
    "verify_manifest",
]
