"""Frozen persistence-v1 schema as of revision 20260814_0001."""

from sqlalchemy import (
    DDL,
    JSON,
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
    event,
    func,
)

metadata = MetaData(naming_convention={
    "ix": "ix_%(table_name)s_%(column_0_name)s", "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s", "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s", "pk": "pk_%(table_name)s",
})


def _created():
    return Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now())


projects = Table("projects", metadata, Column("id", String(64), primary_key=True), Column("name", String(255), nullable=False), Column("description", Text), _created())
users = Table("users", metadata, Column("id", String(64), primary_key=True), Column("project_id", String(64), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), Column("email", String(320)), Column("display_name", String(255)), _created(), UniqueConstraint("project_id", "email", name="project_email"))
artifacts = Table("artifacts", metadata, Column("digest", String(64), primary_key=True), Column("size_bytes", Integer, nullable=False), Column("media_type", String(255), nullable=False, server_default="application/octet-stream"), Column("storage_uri", Text, nullable=False), Column("metadata_json", JSON, nullable=False, default=dict), _created(), CheckConstraint("size_bytes >= 0", name="nonnegative_size"), CheckConstraint("length(digest) = 64", name="sha256_digest"))
study_packs = Table("study_packs", metadata, Column("id", String(64), primary_key=True), Column("project_id", String(64), ForeignKey("projects.id", ondelete="RESTRICT"), nullable=False), Column("pack_key", String(128), nullable=False), Column("version", String(64), nullable=False), Column("content_digest", String(64), ForeignKey("artifacts.digest", ondelete="RESTRICT"), nullable=False), Column("content_metadata", JSON, nullable=False, default=dict), _created(), UniqueConstraint("project_id", "pack_key", "version", name="project_pack_version"), CheckConstraint("length(version) > 0", name="nonempty_version"))
experiments = Table("experiments", metadata, Column("id", String(64), primary_key=True), Column("project_id", String(64), ForeignKey("projects.id", ondelete="RESTRICT"), nullable=False), Column("study_pack_id", String(64), ForeignKey("study_packs.id", ondelete="RESTRICT"), nullable=False), Column("name", String(255), nullable=False), Column("protocol_version", String(32), nullable=False), Column("spec_hash", String(64)), Column("study_pack_hash", String(64)), Column("predecessor_id", String(64), ForeignKey("experiments.id", ondelete="RESTRICT")), Column("owner_approval", String(16), nullable=False, server_default="pending"), Column("definition", JSON, nullable=False, default=dict), Column("frozen_at", DateTime(timezone=True)), _created(), CheckConstraint("owner_approval IN ('pending', 'approved', 'rejected')", name="valid_owner_approval"), CheckConstraint("spec_hash IS NULL OR length(spec_hash) = 64", name="spec_hash_digest"), CheckConstraint("study_pack_hash IS NULL OR length(study_pack_hash) = 64", name="study_pack_hash_digest"))
event.listen(experiments, "after_create", DDL("""CREATE TRIGGER experiments_reject_frozen_updates BEFORE UPDATE ON experiments WHEN OLD.frozen_at IS NOT NULL BEGIN SELECT RAISE(ABORT, 'frozen experiments are immutable'); END""").execute_if(dialect="sqlite"))
event.listen(experiments, "after_create", DDL("""CREATE OR REPLACE FUNCTION scaffold_arena_reject_frozen_experiment_update() RETURNS trigger AS $$ BEGIN IF OLD.frozen_at IS NOT NULL THEN RAISE EXCEPTION 'frozen experiments are immutable'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;""").execute_if(dialect="postgresql"))
event.listen(experiments, "after_create", DDL("""CREATE TRIGGER experiments_reject_frozen_updates BEFORE UPDATE ON experiments FOR EACH ROW EXECUTE FUNCTION scaffold_arena_reject_frozen_experiment_update()""").execute_if(dialect="postgresql"))
executions = Table("executions", metadata, Column("id", String(64), primary_key=True), Column("experiment_id", String(64), ForeignKey("experiments.id", ondelete="RESTRICT"), nullable=False), Column("status", String(32), nullable=False), Column("parameters", JSON, nullable=False, default=dict), Column("started_at", DateTime(timezone=True)), Column("completed_at", DateTime(timezone=True)), _created(), CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled', 'legacy_local_unverified')", name="valid_status"))
episodes = Table("episodes", metadata, Column("id", String(64), primary_key=True), Column("execution_id", String(64), ForeignKey("executions.id", ondelete="CASCADE"), nullable=False), Column("ordinal", Integer, nullable=False), Column("scenario_id", String(128)), Column("metadata_json", JSON, nullable=False, default=dict), _created(), UniqueConstraint("execution_id", "ordinal", name="execution_ordinal"), CheckConstraint("ordinal >= 0", name="nonnegative_ordinal"))
attempts = Table("attempts", metadata, Column("id", String(64), primary_key=True), Column("episode_id", String(64), ForeignKey("episodes.id", ondelete="CASCADE"), nullable=False), Column("ordinal", Integer, nullable=False), Column("status", String(32), nullable=False, server_default="pending"), Column("request_metadata", JSON, nullable=False, default=dict), Column("result_metadata", JSON, nullable=False, default=dict), _created(), UniqueConstraint("episode_id", "ordinal", name="episode_ordinal"), CheckConstraint("ordinal >= 0", name="nonnegative_ordinal"))
jobs = Table("jobs", metadata, Column("id", String(64), primary_key=True), Column("execution_id", String(64), ForeignKey("executions.id", ondelete="CASCADE"), nullable=False), Column("attempt_id", String(64), ForeignKey("attempts.id", ondelete="SET NULL")), Column("kind", String(64), nullable=False), Column("status", String(32), nullable=False, server_default="queued"), Column("lease_owner", String(255)), Column("lease_expires_at", DateTime(timezone=True)), Column("heartbeat_at", DateTime(timezone=True)), Column("attempt_count", Integer), Column("available_at", DateTime(timezone=True)), Column("cancel_requested_at", DateTime(timezone=True)), Column("payload", JSON, nullable=False, default=dict), _created(), CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled')", name="valid_status"), CheckConstraint("attempt_count IS NULL OR attempt_count >= 0", name="nonnegative_attempt_count"))
attempt_events = Table("attempt_events", metadata, Column("id", String(64), primary_key=True), Column("attempt_id", String(64), ForeignKey("attempts.id", ondelete="CASCADE"), nullable=False), Column("sequence", Integer, nullable=False), Column("event_type", String(128), nullable=False), Column("payload", JSON, nullable=False, default=dict), _created(), UniqueConstraint("attempt_id", "sequence", name="attempt_sequence"), CheckConstraint("sequence > 0", name="positive_sequence"))
evaluations = Table("evaluations", metadata, Column("id", String(64), primary_key=True), Column("attempt_id", String(64), ForeignKey("attempts.id", ondelete="CASCADE"), nullable=False), Column("evaluator", String(128), nullable=False), Column("score", Float), Column("result", JSON, nullable=False, default=dict), _created())
annotations = Table("annotations", metadata, Column("id", String(64), primary_key=True), Column("attempt_id", String(64), ForeignKey("attempts.id", ondelete="CASCADE"), nullable=False), Column("user_id", String(64), ForeignKey("users.id", ondelete="SET NULL")), Column("kind", String(64), nullable=False), Column("body", JSON, nullable=False, default=dict), _created())
evidence_receipts = Table("evidence_receipts", metadata, Column("id", String(64), primary_key=True), Column("execution_id", String(64), ForeignKey("executions.id", ondelete="RESTRICT")), Column("artifact_digest", String(64), ForeignKey("artifacts.digest", ondelete="RESTRICT"), nullable=False), Column("receipt_kind", String(64), nullable=False), Column("claims", JSON, nullable=False, default=list), _created())
reproductions = Table("reproductions", metadata, Column("id", String(64), primary_key=True), Column("source_execution_id", String(64), ForeignKey("executions.id", ondelete="RESTRICT"), nullable=False), Column("reproduction_execution_id", String(64), ForeignKey("executions.id", ondelete="RESTRICT")), Column("status", String(32), nullable=False), Column("result", JSON, nullable=False, default=dict), _created())
audit_events = Table("audit_events", metadata, Column("id", String(64), primary_key=True), Column("project_id", String(64), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), Column("actor_user_id", String(64), ForeignKey("users.id", ondelete="SET NULL")), Column("event_type", String(128), nullable=False), Column("payload", JSON, nullable=False, default=dict), _created())
idempotency_records = Table("idempotency_records", metadata, Column("id", String(64), primary_key=True), Column("project_id", String(64), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), Column("key", String(255), nullable=False), Column("request_digest", String(64), nullable=False), Column("response", JSON, nullable=False, default=dict), _created(), UniqueConstraint("project_id", "key", name="project_key"), CheckConstraint("length(request_digest) = 64", name="request_digest"))
usage_ledger = Table("usage_ledger", metadata, Column("id", String(64), primary_key=True), Column("execution_id", String(64), ForeignKey("executions.id", ondelete="CASCADE"), nullable=False), Column("attempt_id", String(64), ForeignKey("attempts.id", ondelete="SET NULL")), Column("model_id", String(255), nullable=False), Column("input_tokens", Integer, nullable=False, server_default="0"), Column("output_tokens", Integer, nullable=False, server_default="0"), Column("cost_status", String(16), nullable=False), Column("cost_usd", Float), Column("reserved_cost_usd", Float), Column("estimated_cost_usd", Float), Column("actual_cost_usd", Float), Column("price_catalog_revision", String(128)), Column("provider_usage_digest", String(64)), _created(), CheckConstraint("input_tokens >= 0 AND output_tokens >= 0", name="nonnegative_usage"), CheckConstraint("cost_status IN ('reserved', 'estimated', 'reconciled', 'unknown', 'mismatch')", name="valid_cost_status"), CheckConstraint("cost_status != 'unknown' OR (cost_usd IS NULL AND actual_cost_usd IS NULL)", name="unknown_cost_is_null"), CheckConstraint("cost_status != 'reconciled' OR (cost_usd IS NOT NULL AND actual_cost_usd IS NOT NULL AND price_catalog_revision IS NOT NULL AND provider_usage_digest IS NOT NULL AND length(provider_usage_digest) = 64)", name="reconciled_cost_evidence"), CheckConstraint("(cost_usd IS NULL OR cost_usd >= 0) AND (reserved_cost_usd IS NULL OR reserved_cost_usd >= 0) AND (estimated_cost_usd IS NULL OR estimated_cost_usd >= 0) AND (actual_cost_usd IS NULL OR actual_cost_usd >= 0)", name="nonnegative_costs"))
price_catalog = Table("price_catalog", metadata, Column("id", String(64), primary_key=True), Column("revision", String(128), nullable=False), Column("model_id", String(255), nullable=False), Column("provider", String(128), nullable=False), Column("input_usd_per_million", Float, nullable=False), Column("output_usd_per_million", Float, nullable=False), Column("effective_at", DateTime(timezone=True), nullable=False), Column("source", Text, nullable=False), _created(), UniqueConstraint("revision", "model_id", "provider", "effective_at", name="revision_model_provider_effective"), CheckConstraint("input_usd_per_million >= 0 AND output_usd_per_million >= 0", name="nonnegative_prices"))

Index("ix_study_packs_project_pack", study_packs.c.project_id, study_packs.c.pack_key)
Index("ix_executions_experiment_created", executions.c.experiment_id, executions.c.created_at)
Index("ix_attempt_events_attempt_sequence", attempt_events.c.attempt_id, attempt_events.c.sequence)
Index("ix_jobs_status_available", jobs.c.status, jobs.c.available_at)
Index("ix_audit_events_project_created", audit_events.c.project_id, audit_events.c.created_at)
Index("ix_usage_ledger_execution_created", usage_ledger.c.execution_id, usage_ledger.c.created_at)
