import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'

import { type ArenaV1Client } from '../../journeys/study-design-preflight/types'
import { ReviewSurface } from './ReviewSurface'

const batch = { batch_id: 'batch-1', status: 'PENDING', assignment_count: 1, claim_ceiling: 'blind only' }
function client(content: object = { rubric: { dimensions: [{ metric_id: 'quality', instruction: 'score quality', anchor_0: 'poor', anchor_1: 'good' }] }, output: 'visible output' }): ArenaV1Client {
  return { review: { list: vi.fn().mockResolvedValue({ annotation_batches: [batch] }), getBatch: vi.fn().mockResolvedValue({ batch_id: 'batch-1', status: 'PENDING', claim_ceiling: 'blind only', conflicted_dimensions: {}, assignments: [{ assignment_id: 'assignment-1', item_id: 'item-1', blind_payload_digest: 'a'.repeat(64) }] }), getAssignment: vi.fn().mockResolvedValue({ assignment_id: 'assignment-1', item_id: 'item-1', blind_payload_digest: 'a'.repeat(64), blinded_content: content }), submitAnnotation: vi.fn().mockResolvedValue({}), submitAdjudication: vi.fn(), createBatch: vi.fn() } } as unknown as ArenaV1Client
}
describe('ReviewSurface', () => {
  it('requires a pseudonym before it requests a blind batch', async () => { const arena = client(); render(<ReviewSurface client={arena} mode="guided" />); await screen.findByText('Batch 1'); fireEvent.click(screen.getByRole('button', { name: 'Open blind batch' })); expect(arena.review.getBatch).not.toHaveBeenCalled(); expect(screen.getByText('Review HOLD')).toBeInTheDocument() })
  it('does not render a blind payload that leaks scaffold context', async () => { const arena = client({ scaffold_id: 'leak' }); render(<ReviewSurface client={arena} mode="guided" />); await screen.findByText('Batch 1'); fireEvent.change(screen.getByLabelText('Reviewer pseudonym'), { target: { value: 'reviewer-a' } }); fireEvent.click(screen.getByRole('button', { name: 'Open blind batch' })); await screen.findByText('Assignment 1'); fireEvent.click(screen.getByRole('button', { name: 'Open blinded content' })); expect((await screen.findAllByText(/Blindness HOLD/)).length).toBeGreaterThan(0); expect(screen.queryByText('leak')).not.toBeInTheDocument() })
  it('uses rubric dimensions for the exact immutable annotation payload without exposing Guided raw IDs or JSON', async () => { const arena = client(); render(<ReviewSurface client={arena} mode="guided" projectId="project-1" />); await screen.findByText('Batch 1'); fireEvent.change(screen.getByLabelText('Reviewer pseudonym'), { target: { value: 'reviewer-a' } }); fireEvent.click(screen.getByRole('button', { name: 'Open blind batch' })); await screen.findByText('Assignment 1'); fireEvent.click(screen.getByRole('button', { name: 'Open blinded content' })); const score = await screen.findByRole('spinbutton'); fireEvent.change(score, { target: { value: '0.8' } }); await waitFor(() => expect(screen.getByRole('button', { name: 'Submit immutable annotation' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: 'Submit immutable annotation' })); await waitFor(() => expect(arena.review.submitAnnotation).toHaveBeenCalledWith('batch-1', { assignment_id: 'assignment-1', annotator_pseudonym: 'reviewer-a', dimension_scores: { quality: 0.8 } }, { projectId: 'project-1' })); expect(screen.queryByText('batch-1')).not.toBeInTheDocument(); expect(screen.queryByText('assignment-1')).not.toBeInTheDocument(); expect(screen.queryByText('visible output')).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Submit adjudication' })).not.toBeInTheDocument() })
})
