import { useCallback, useEffect, useMemo, useState } from 'react'

import { ApiProblem, createArenaV1, type AdjudicationSubmission, type AnnotationBatch, type AnnotationBatchView, type AnnotationSubmission, type AssignmentView, type JsonObject } from '../../../api/v1/client'
import { SevereFailureBanner, StatusIndicator, WorkbenchButton, WorkbenchPanel, WorkbenchState, WorkbenchTable } from '../../design-system'

import './review.css'

type Client = ReturnType<typeof createArenaV1>
type State = 'loading' | 'ready' | 'empty' | 'offline' | 'permission' | 'hold' | 'error'
const forbidden = ['treatment', 'harness', 'factor', 'scaffold', 'adapter', 'control_plane', 'controlplane']

export interface ReviewSurfaceProps { client: Client; projectId?: string; mode: 'guided' | 'lab' }
function issue(error: unknown): { state: Exclude<State, 'loading' | 'ready' | 'empty'>; message: string } {
  if (error instanceof ApiProblem) {
    if (error.isHold) return { state: 'hold', message: error.message }
    if (error.status === 401 || error.status === 403 || error.code === 'project_context_required' || error.code === 'unknown_project') return { state: 'permission', message: error.message }
    return { state: error.status >= 500 ? 'offline' : 'error', message: error.message }
  }
  return { state: 'offline', message: error instanceof Error ? error.message : 'Review service unavailable.' }
}
function parse<T>(text: string): T | null { try { return JSON.parse(text) as T } catch { return null } }
function leaks(value: unknown): boolean {
  if (Array.isArray(value)) return value.some(leaks)
  if (value && typeof value === 'object') return Object.entries(value).some(([key, child]) => forbidden.some((term) => key.toLowerCase().includes(term)) || leaks(child))
  return false
}
function dimensions(assignment: AssignmentView | null): Array<{ metric_id: string; instruction: string; anchor_0: string; anchor_1: string }> {
  const source = assignment?.blinded_content.rubric
  if (!source || typeof source !== 'object' || Array.isArray(source)) return []
  const raw = (source as JsonObject).dimensions
  return Array.isArray(raw) ? raw.filter((item): item is JsonObject => Boolean(item) && typeof item === 'object' && !Array.isArray(item)).flatMap((item) => typeof item.metric_id === 'string' && typeof item.instruction === 'string' && typeof item.anchor_0 === 'string' && typeof item.anchor_1 === 'string' ? [{ metric_id: item.metric_id, instruction: item.instruction, anchor_0: item.anchor_0, anchor_1: item.anchor_1 }] : []) : []
}

export function ReviewSurface({ client, projectId, mode }: ReviewSurfaceProps) {
  const [state, setState] = useState<State>('loading'); const [message, setMessage] = useState('')
  const [batches, setBatches] = useState<Awaited<ReturnType<Client['review']['list']>>['annotation_batches']>([])
  const [pseudonym, setPseudonym] = useState(''); const [batch, setBatch] = useState<AnnotationBatchView | null>(null); const [assignment, setAssignment] = useState<AssignmentView | null>(null)
  const [scores, setScores] = useState<Record<string, string>>({}); const [labSubmission, setLabSubmission] = useState(''); const [labBatch, setLabBatch] = useState(''); const [adjudication, setAdjudication] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setState('loading'); try { const found = await client.review.list({}, { projectId }); setBatches(found.annotation_batches); setState(found.annotation_batches.length ? 'ready' : 'empty'); setMessage('') } catch (error) { const next = issue(error); setState(next.state); setMessage(next.message) } }, [client, projectId])
  useEffect(() => { void load() }, [load])
  const openBatch = async (id: string) => { if (!pseudonym.trim()) { setState('hold'); setMessage('A reviewer pseudonym is required before any blind batch or assignment view.'); return } setBusy(true); try { setBatch(await client.review.getBatch(id, pseudonym.trim(), { projectId })); setAssignment(null); setState('ready'); setMessage('') } catch (error) { const next = issue(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const openAssignment = async (id: string) => { if (!batch || !pseudonym.trim()) return; setBusy(true); setAssignment(null); try { const found = await client.review.getAssignment(batch.batch_id, id, pseudonym.trim(), { projectId }); if (leaks(found.blinded_content)) { setState('hold'); setMessage('Blindness HOLD: the returned payload contains a forbidden treatment, harness, factor, scaffold, or adapter field and will not be rendered.'); return } setAssignment(found); setScores({}); setLabSubmission(''); setState('ready') } catch (error) { const next = issue(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const rubric = useMemo(() => dimensions(assignment), [assignment]); const conflicting = Boolean(batch && assignment && (batch.conflicted_dimensions[assignment.item_id] ?? []).length)
  const submit = async () => { if (!batch || !assignment) return; const guidedScores = rubric.map((dimension) => [dimension.metric_id, Number(scores[dimension.metric_id])] as const); if (mode === 'guided' && guidedScores.some(([, score]) => !Number.isFinite(score) || score < 0 || score > 1)) { setState('hold'); setMessage('Every guided rubric score must be a finite number from 0 through 1.'); return } const payload: AnnotationSubmission | null = mode === 'lab' ? parse<AnnotationSubmission>(labSubmission) : rubric.length ? { assignment_id: assignment.assignment_id, annotator_pseudonym: pseudonym.trim(), dimension_scores: Object.fromEntries(guidedScores) } : null; if (!payload) { setState('hold'); setMessage(mode === 'lab' ? 'Submission JSON is invalid. Supply exactly the server annotation contract.' : 'The blinded rubric dimensions are unavailable; use Lab JSON only with a server-valid canonical submission.'); return } setBusy(true); try { await client.review.submitAnnotation(batch.batch_id, payload, { projectId }); await openBatch(batch.batch_id); setMessage('Immutable annotation submitted or replayed by the server.') } catch (error) { const next = issue(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const submitAdjudication = async () => { if (!batch || !assignment || !conflicting) return; const payload = parse<AdjudicationSubmission>(adjudication); if (!payload) { setState('hold'); setMessage('Adjudication JSON is invalid; submit only the exact server contract with the bound blinded artifact digest.'); return } setBusy(true); try { await client.review.submitAdjudication(batch.batch_id, payload, { projectId }); await openBatch(batch.batch_id); setMessage('Server adjudication recorded or replayed.') } catch (error) { const next = issue(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const create = async () => { const payload = parse<AnnotationBatch>(labBatch); if (!payload) { setState('hold'); setMessage('Batch JSON is invalid. Guided mode never invents a grader plan, rubric, pseudonyms, or items.'); return } setBusy(true); try { await client.review.createBatch(payload, { projectId }); await load(); setMessage('Batch admitted by the server.') } catch (error) { const next = issue(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }

  if (state === 'loading') return <WorkbenchState kind="loading" title="Recovering durable blind review batches">Loading redacted project-scoped summaries only.</WorkbenchState>
  if (state === 'offline') return <WorkbenchState kind="offline" title="Review recovery unavailable" action={<WorkbenchButton onClick={() => void load()}>Retry recovery</WorkbenchButton>}>{message}</WorkbenchState>
  if (state === 'permission') return <SevereFailureBanner title="Project context required" action={<WorkbenchButton onClick={() => void load()}>Retry with project context</WorkbenchButton>}>{message}</SevereFailureBanner>
  return <section className="sa-review" aria-labelledby="review-heading">
    <SevereFailureBanner title="Reviewer identity remains unverified">Blind-review completion is not human validation or independent validation. The claim ceiling remains server-reported.</SevereFailureBanner>
    <WorkbenchPanel title={<span id="review-heading">Blind review</span>} action={<StatusIndicator tone="warning">identity_unverified</StatusIndicator>}><label className="sa-review-field">Reviewer pseudonym<input value={pseudonym} onChange={(event) => setPseudonym(event.target.value)} autoComplete="off" /></label><p>Required before selecting a blind batch. Treatment, harness, factor, scaffold, adapter, and control-plane data are never rendered.</p>{message && <p role="status">{message}</p>}</WorkbenchPanel>
    {state === 'hold' && <SevereFailureBanner title="Review HOLD">{message}</SevereFailureBanner>}
    {state === 'error' && <WorkbenchState kind="error" title="Review operation failed" action={<WorkbenchButton onClick={() => void load()}>Reload batches</WorkbenchButton>}>{message}</WorkbenchState>}
    {state === 'empty' && <WorkbenchState kind="empty" title="No durable review batches">Lab can submit a canonical server-valid batch. Guided mode cannot create a grader plan or rubric.</WorkbenchState>}
    <WorkbenchPanel title="Durable batch recovery"><WorkbenchTable><thead><tr><th scope="col">Batch</th><th scope="col">Status</th><th scope="col">Assignments</th><th scope="col">Ceiling</th><th scope="col">Select</th></tr></thead><tbody>{batches.map((item, index) => <tr key={item.batch_id}><td>{mode === 'lab' ? <code>{item.batch_id}</code> : `Batch ${index + 1}`}</td><td>{item.status}</td><td>{item.assignment_count}</td><td>{item.claim_ceiling}</td><td><WorkbenchButton disabled={busy} onClick={() => void openBatch(item.batch_id)}>Open blind batch</WorkbenchButton></td></tr>)}</tbody></WorkbenchTable></WorkbenchPanel>
    {mode === 'lab' && <WorkbenchPanel title="Create batch (Lab canonical JSON)"><label className="sa-review-field">AnnotationBatch JSON<textarea value={labBatch} onChange={(event) => setLabBatch(event.target.value)} spellCheck={false} /></label><WorkbenchButton disabled={busy} onClick={() => void create()}>Submit canonical batch</WorkbenchButton></WorkbenchPanel>}
    {batch && <WorkbenchPanel title={mode === 'lab' ? `Assignments for ${batch.batch_id}` : 'Assignments for selected batch'} action={<StatusIndicator tone="warning">{batch.claim_ceiling}</StatusIndicator>}><WorkbenchTable><thead><tr><th scope="col">Assignment</th><th scope="col">Item</th><th scope="col">Blind record</th><th scope="col">Open</th></tr></thead><tbody>{batch.assignments.map((item, index) => <tr key={item.assignment_id}><td>{mode === 'lab' ? <code>{item.assignment_id}</code> : `Assignment ${index + 1}`}</td><td>{mode === 'lab' ? item.item_id : `Blinded item ${index + 1}`}</td><td>{mode === 'lab' ? <code>{item.blind_payload_digest}</code> : 'Bound blinded record'}</td><td><WorkbenchButton disabled={busy} onClick={() => void openAssignment(item.assignment_id)}>Open blinded content</WorkbenchButton></td></tr>)}</tbody></WorkbenchTable></WorkbenchPanel>}
    {assignment && <WorkbenchPanel title={mode === 'lab' ? `Blinded assignment ${assignment.item_id}` : 'Selected blinded assignment'}>{mode === 'lab' ? <pre className="sa-review-content">{JSON.stringify(assignment.blinded_content, null, 2)}</pre> : <p>The server-provided blinded content is available only through the rubric controls below. Raw payload JSON and durable identifiers remain in Lab.</p>}{rubric.length ? <div className="sa-review-scores">{rubric.map((dimension) => <label key={dimension.metric_id}>{dimension.metric_id}: {dimension.instruction}<small>0: {dimension.anchor_0} · 1: {dimension.anchor_1}</small><input type="number" min="0" max="1" step="0.01" value={scores[dimension.metric_id] ?? ''} onChange={(event) => setScores((current) => ({ ...current, [dimension.metric_id]: event.target.value }))} /></label>)}</div> : <p>Rubric dimensions are unavailable in this blinded payload. Guided scoring is unavailable.</p>}{mode === 'lab' && <label className="sa-review-field">AnnotationSubmission JSON<textarea value={labSubmission} onChange={(event) => setLabSubmission(event.target.value)} spellCheck={false} /></label>}<WorkbenchButton tone="primary" disabled={busy || (mode === 'guided' && (!rubric.length || rubric.some((dimension) => !scores[dimension.metric_id])))} onClick={() => void submit()}>Submit immutable annotation</WorkbenchButton>{conflicting && mode === 'lab' && <><h3>Server-reported conflict requires adjudication</h3><p>Only conflicted dimensions may be adjudicated; evidence digest must be the bound blinded artifact.</p><label className="sa-review-field">AdjudicationSubmission JSON<textarea value={adjudication} onChange={(event) => setAdjudication(event.target.value)} placeholder={`{"item_id":"${assignment.item_id}","evidence_artifact_digest":"${assignment.blind_payload_digest}"}`} spellCheck={false} /></label><WorkbenchButton disabled={busy} onClick={() => void submitAdjudication()}>Submit adjudication</WorkbenchButton></>}{conflicting && mode === 'guided' && <SevereFailureBanner title="Adjudication requires Lab review">Cause: the server reported a conflicting blind dimension. Consequence: Guided mode cannot construct canonical adjudication evidence. Remediation: open this blinded assignment in Lab with the bound durable record.</SevereFailureBanner>}</WorkbenchPanel>}
  </section>
}
