#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Iterable

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PHRASES = {
    "README.md": [
        "Not supported:",
        "A fixture sample is a live benchmark result.",
        "A synthetic source is a real publication.",
    ],
    "docs/huggingface/README.md": [
        "What This Does Not Contain",
        "Live provider benchmark results.",
        "Human annotation results.",
        "Independent reproduction or public critique evidence.",
    ],
    "docs/benchmarking/benchmark_card.md": [
        "Unsupported Claims",
        "Fixture artifacts are live benchmark results.",
        "An external-validation ledger with zero records is external validation evidence.",
    ],
    "docs/benchmarking/reproducibility.md": [
        "It does not prove live model performance unless run artifacts were generated by actual provider runs",
        "does not lift any external-validation cap until concrete external evidence is recorded",
    ],
    "docs/reviews/external-validation-ledger.md": [
        "Independent reproductions: 0.",
        "Human annotation batches: 0.",
        "Status: `no_external_validation_completed`.",
    ],
    "docs/evidence-status.md": [
        "Live provider study | Not yet recorded",
        "Human calibration | Not yet completed",
        "Independent reproduction | Not yet completed",
    ],
}

FORBIDDEN_REGEXES = [
    re.compile(r"\bfixture(?:s| artifacts?| samples?)\s+(?:are|is|prove|proves|show|shows)\s+live\b", re.I),
    re.compile(r"\bsynthetic sources?\s+(?:are|is)\s+real publications?\b", re.I),
    re.compile(r"\bhuman calibration has been completed\b", re.I),
    re.compile(r"\bindependent reproduction has been completed\b", re.I),
    re.compile(r"\bexternal validation has been completed\b", re.I),
    re.compile(r"\bexternally validated benchmark\b", re.I),
    re.compile(r"\bpublished Hugging Face dataset\b", re.I),
    re.compile(r"\btypical score\b", re.I),
    re.compile(
        r"\b(?:quality|score) improvement(?:s)?\b.{0,80}\b(?:usually|often)\s+exponential\b"
        r"|\b(?:usually|often)\s+exponential\b.{0,80}\b(?:quality|score) improvement(?:s)?\b",
        re.I,
    ),
    re.compile(
        r"\b(?:score|quality) improvement(?:s)?\b.{0,80}\b\d+(?:[.-]|–)\d+x\b"
        r"|\b\d+(?:[.-]|–)\d+x\b.{0,80}\b(?:score|quality) improvement(?:s)?\b",
        re.I,
    ),
]
EMPIRICAL_RESULT_REGEXES = frozenset(FORBIDDEN_REGEXES[-3:])

ALLOWED_FORBIDDEN_CONTEXTS = [
    "not supported",
    "unsupported claims",
    "what this does not contain",
    "not honest yet",
    "blocker",
    "blockers",
    "claim boundary",
    "does not",
    "do not",
    "not a",
    "not live",
    "not published",
    "zero completed",
    "hypothesis",
    "hypotheses",
    "requires empirical",
    "requires a study",
    "requires study",
    "would require",
    "may be",
    "might be",
    "should not be read as",
]

RELEASE_MARKDOWN_TARGETS = [
    "README.md",
    "docs/protocol/scaffold-arena-protocol.md",
    "docs/benchmarking/benchmark_card.md",
    "docs/benchmarking/reproducibility.md",
    "docs/benchmarking/comparison_to_existing_tools.md",
    "docs/benchmarking/public_release_checklist.md",
    "docs/huggingface/README.md",
    "docs/paper/scaffold_arena_protocol_v0_1.md",
    "docs/reviews/external-validation-ledger.md",
    "docs/evidence-status.md",
]


def tracked_markdown_paths(root: Path = ROOT) -> list[str]:
    """Return the complete tracked Markdown inventory for the candidate tree."""

    def git_paths(arguments: list[str]) -> set[str]:
        result = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z", *arguments, "--", "*.md"],
            check=False,
            capture_output=True,
        )
        if result.returncode:
            detail = result.stderr.decode("utf-8", errors="replace").strip()
            raise RuntimeError(f"could not list tracked Markdown files: {detail}")
        return {path for path in result.stdout.decode("utf-8").split("\0") if path}

    return sorted(git_paths(["--cached"]) - git_paths(["--deleted"]))


def _load_json(path: str) -> Any:
    return json.loads((ROOT / path).read_text())


def _line_has_allowed_context(text: str, line_number: int) -> bool:
    lines = text.splitlines()
    start = max(0, line_number - 6)
    end = min(len(lines), line_number + 3)
    context = "\n".join(lines[start:end]).lower()
    return any(allowed in context for allowed in ALLOWED_FORBIDDEN_CONTEXTS)


def _line_explicitly_bounds_empirical_claim(line: str) -> bool:
    lowered = line.lower()
    if "hypothesis" in lowered or "requires empirical" in lowered or "requires a study" in lowered:
        return True
    if re.search(r"\b(?:fixture|synthetic)\b.{0,80}\b(?:field|schema|expected|example|test)\b", lowered):
        return True
    return bool(
        re.search(
            r"\b(?:does|do|did)\s+not\s+"
            r"(?:claim|show|prove|establish|demonstrate|support|report)\b.{0,100}"
            r"\b(?:typical score|(?:score|quality) improvement)\b",
            lowered,
        )
        or re.search(
            r"\b(?:do not|don't)\s+(?:claim|show|prove|establish|demonstrate|support|report)\b"
            r".{0,100}\b(?:typical score|(?:score|quality) improvement)\b",
            lowered,
        )
    )


def _check_required_phrases() -> list[str]:
    errors: list[str] = []
    for relative_path, phrases in REQUIRED_PHRASES.items():
        text = (ROOT / relative_path).read_text()
        for phrase in phrases:
            if phrase not in text:
                errors.append(f"{relative_path}: missing required claim-boundary phrase: {phrase}")
    return errors


def _check_forbidden_phrases(
    root: Path = ROOT, markdown_paths: Iterable[str] | None = None
) -> list[str]:
    errors: list[str] = []
    paths = sorted(markdown_paths) if markdown_paths is not None else tracked_markdown_paths(root)
    for relative_path in paths:
        text = (root / relative_path).read_text(encoding="utf-8")
        for line_index, line in enumerate(text.splitlines(), start=1):
            for pattern in FORBIDDEN_REGEXES:
                if not pattern.search(line):
                    continue
                if pattern in EMPIRICAL_RESULT_REGEXES and _line_explicitly_bounds_empirical_claim(line):
                    continue
                if pattern in EMPIRICAL_RESULT_REGEXES:
                    errors.append(f"{relative_path}:{line_index}: unsupported public claim: {line.strip()}")
                    continue
                if _line_has_allowed_context(text, line_index):
                    continue
                errors.append(f"{relative_path}:{line_index}: unsupported public claim: {line.strip()}")
    return errors


def _check_machine_boundaries() -> list[str]:
    errors: list[str] = []
    external = _load_json("outputs/external_validation.json")
    if external.get("status") != "no_external_validation_completed":
        errors.append("external validation ledger must remain no_external_validation_completed without evidence records")
    evidence_count = (
        len(external.get("independent_reproductions", []))
        + len(external.get("public_critiques", []))
        + len(external.get("human_annotation_batches", []))
    )
    if evidence_count != 0:
        errors.append("external validation ledger contains evidence records; update claim-boundary checks before release")

    external_audit = _load_json("outputs/external_validation_audit.json")
    if external_audit.get("status") != "blocked_no_external_validation":
        errors.append("external validation audit must remain blocked_no_external_validation without evidence records")
    if external_audit.get("evidence_count") != 0:
        errors.append("external validation audit unexpectedly claims external evidence")
    external_audit_boundary = str(external_audit.get("claim_boundary", "")).lower()
    for phrase in ["not external validation evidence", "not live benchmark evidence", "not human calibration evidence"]:
        if phrase not in external_audit_boundary:
            errors.append(f"external validation audit missing claim-boundary phrase: {phrase}")

    leakage = _load_json("outputs/benchmark_leakage_audit.json")
    if leakage.get("status") != "benchmark_leakage_audit_passed_fixture_contract_not_hidden_test":
        errors.append("benchmark leakage audit must pass before public release")
    for key in [
        "scenario_prompt_leak_count",
        "task_prompt_leak_count",
        "artifact_output_leak_count",
        "scenario_role_mismatch_count",
    ]:
        if leakage.get(key) != 0:
            errors.append(f"benchmark leakage audit {key} must be 0")
    leakage_boundary = str(leakage.get("claim_boundary", "")).lower()
    for phrase in ["not a guarantee", "not live benchmark evidence", "not human calibration", "not external validation"]:
        if phrase not in leakage_boundary:
            errors.append(f"benchmark leakage audit missing claim-boundary phrase: {phrase}")

    hf = _load_json("outputs/huggingface_package_manifest.json")
    if hf.get("status") != "hf_ready_fixture_package_not_published_not_live_benchmark":
        errors.append("HF package manifest must not claim publication or live benchmark status")

    prior_art = _load_json("outputs/prior_art_positioning_audit.json")
    if prior_art.get("status") != "source_backed_prior_art_positioning_not_external_validation":
        errors.append("prior-art audit must remain positioning evidence, not external validation")
    prior_text = json.dumps(prior_art).lower()
    for phrase in ["not external validation evidence", "not adoption evidence", "not proof of field influence"]:
        if phrase not in prior_text:
            errors.append(f"prior-art audit missing claim-boundary phrase: {phrase}")

    preflight = _load_json("outputs/live_benchmark_preflight.json")
    if preflight.get("status") != "static_live_benchmark_preflight_not_live_evidence":
        errors.append("live preflight must remain a static readiness artifact")

    live_evidence = _load_json("outputs/live_evidence_audit.json")
    if live_evidence.get("status") != "blocked_no_live_artifacts":
        errors.append("live evidence audit must remain blocked_no_live_artifacts without live artifacts")
    if live_evidence.get("live_run_count") != 0:
        errors.append("live evidence audit unexpectedly claims live artifacts in keyless release state")
    live_evidence_boundary = str(live_evidence.get("claim_boundary", "")).lower()
    for phrase in ["not live benchmark evidence", "not human calibration", "external validation"]:
        if phrase not in live_evidence_boundary:
            errors.append(f"live evidence audit missing claim-boundary phrase: {phrase}")

    calibration = _load_json("outputs/human_calibration_packet.json")
    if calibration.get("status") != "annotation_packet_ready_not_human_evidence":
        errors.append("human calibration packet must not claim completed human evidence")

    calibration_audit = _load_json("outputs/human_calibration_audit.json")
    if calibration_audit.get("status") != "blocked_no_completed_annotations":
        errors.append("human calibration audit must remain blocked_no_completed_annotations without annotations")
    if calibration_audit.get("annotation_count") != 0:
        errors.append("human calibration audit unexpectedly claims completed annotation evidence")
    calibration_audit_boundary = str(calibration_audit.get("claim_boundary", "")).lower()
    for phrase in ["not human calibration evidence", "not live benchmark evidence", "not external validation evidence"]:
        if phrase not in calibration_audit_boundary:
            errors.append(f"human calibration audit missing claim-boundary phrase: {phrase}")

    bundle = _load_json("outputs/release_bundle_audit.json")
    if bundle.get("status") != "release_bundle_audit_passed_not_archive_not_clean_clone":
        errors.append("release bundle audit must pass without claiming archive publication")
    for key in [
        "missing_manifest_coverage_count",
        "duplicate_path_count",
        "invalid_path_count",
        "missing_file_count",
        "disallowed_path_count",
        "private_path_hit_count",
    ]:
        if bundle.get(key) != 0:
            errors.append(f"release bundle audit {key} must be 0")
    bundle_boundary = str(bundle.get("claim_boundary", "")).lower()
    for phrase in ["not a published archive", "not a clean clone proof", "not live benchmark", "not external validation"]:
        if phrase not in bundle_boundary:
            errors.append(f"release bundle audit missing claim-boundary phrase: {phrase}")

    return errors


def main() -> int:
    errors: list[str] = []
    errors.extend(_check_required_phrases())
    try:
        markdown_paths = tracked_markdown_paths(ROOT)
    except RuntimeError as exc:
        print(f"[claim-boundaries] FAIL: {exc}", file=sys.stderr)
        return 1
    errors.extend(_check_forbidden_phrases(ROOT, markdown_paths))
    errors.extend(_check_machine_boundaries())

    if errors:
        for error in errors:
            print(f"[claim-boundaries] FAIL: {error}", file=sys.stderr)
        return 1
    print(f"[claim-boundaries] checked {len(markdown_paths)} tracked Markdown files and 10 machine ledgers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
