import { useCallback, useEffect, useState } from 'react'

import { ApiProblem, createArenaV1, type DecisionAdmissionRequest, type DecisionBriefDetail, type EvidenceReceiptDetail, type EvidenceVerification, type JsonObject, type ReproductionRequest } from '../../../api/v1/client'
import { DisclosureRow, SevereFailureBanner, StatusIndicator, WorkbenchButton, WorkbenchPanel, WorkbenchState, WorkbenchTable } from '../../design-system'

import './evidence.css'

type Client = ReturnType<typeof createArenaV1>
type State = 'loading' | 'ready' | 'empty' | 'offline' | 'permission' | 'hold' | 'error'
export interface EvidenceSurfaceProps { client: Client; projectId?: string; mode: 'guided' | 'lab'; executionId?: string | null; reportDigest?: string | null }
function problem(error: unknown): { state: Exclude<State, 'loading' | 'ready' | 'empty'>; message: string } { if (error instanceof ApiProblem) { if (error.isHold) return { state: 'hold', message: error.message }; if (error.status === 401 || error.status === 403 || error.code === 'project_context_required' || error.code === 'unknown_project') return { state: 'permission', message: error.message }; return { state: error.status >= 500 ? 'offline' : 'error', message: error.message } } return { state: 'offline', message: error instanceof Error ? error.message : 'Evidence service unavailable.' } }
function json<T>(value: string): T | null { try { return JSON.parse(value) as T } catch { return null } }
function receiptStep(kind: string): number { return kind === 'fixture' || kind === 'derived_fixture' ? 1 : kind === 'local_live' || kind === 'derived_local_live' ? 2 : kind === 'reproduction' ? 3 : kind === 'cross_model' ? 4 : kind === 'human_calibration' ? 5 : kind === 'independent_reproduction' ? 6 : 0 }

export function EvidenceSurface({ client, projectId, mode, executionId, reportDigest }: EvidenceSurfaceProps) {
  const [state, setState] = useState<State>('loading'); const [message, setMessage] = useState(''); const [items, setItems] = useState<Awaited<ReturnType<Client['evidence']['list']>>['evidence']>([]); const [detail, setDetail] = useState<EvidenceReceiptDetail | null>(null); const [verification, setVerification] = useState<EvidenceVerification | null>(null); const [decisions, setDecisions] = useState<Awaited<ReturnType<Client['decisionBriefs']['list']>>['decision_briefs']>([]); const [selectedDecision, setSelectedDecision] = useState<DecisionBriefDetail | null>(null); const [executionDraft, setExecutionDraft] = useState(executionId ?? ''); const [requestKey, setRequestKey] = useState(''); const [recordDraft, setRecordDraft] = useState(''); const [reproductionDraft, setReproductionDraft] = useState(''); const [decisionDraft, setDecisionDraft] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { setExecutionDraft(executionId ?? '') }, [executionId])
  const load = useCallback(async () => { setState('loading'); try { const [evidence, briefs] = await Promise.all([client.evidence.list({ ...(executionId ? { executionId } : {}) }, { projectId }), client.decisionBriefs.list({ ...(executionId ? { executionId } : {}), ...(reportDigest ? { reportDigest } : {}) }, { projectId })]); setItems(evidence.evidence); setDecisions(briefs.decision_briefs); setState(evidence.evidence.length || briefs.decision_briefs.length ? 'ready' : 'empty'); setMessage('') } catch (error) { const next = problem(error); setState(next.state); setMessage(next.message) } }, [client, executionId, projectId, reportDigest])
  useEffect(() => { void load() }, [load])
  const inspect = async (id: string) => { setBusy(true); try { setDetail(await client.evidence.get(id, { projectId })); setVerification(null); setState('ready') } catch (error) { const next = problem(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const verify = async () => { if (!detail) return; setBusy(true); try { const current = await client.evidence.verify(detail.receipt_id, { projectId }); setVerification(current); if (!current.verified) { setState('hold'); setMessage(`Verification failed: ${current.errors.join('; ') || 'unknown integrity failure'}`) } } catch (error) { const next = problem(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const derive = async () => { if (!executionDraft || !requestKey) { setState('hold'); setMessage('Derivation requires explicit persisted execution_id and request_key.'); return } setBusy(true); try { await client.evidence.derive({ execution_id: executionDraft, request_key: requestKey }, { projectId }); await load(); setMessage('Derived receipt recovered from durable execution evidence.') } catch (error) { const next = problem(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const record = async () => { const payload = json<JsonObject>(recordDraft); if (!payload) { setState('hold'); setMessage('Evidence JSON is invalid. This surface never invents a manifest, receipt, hash, class, or evidence type.'); return } setBusy(true); try { await client.evidence.record(payload as never, { projectId }); await load(); setMessage('Server admitted the supplied canonical evidence receipt.') } catch (error) { const next = problem(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const reproduce = async () => { const payload = json<ReproductionRequest>(reproductionDraft); if (!payload) { setState('hold'); setMessage('Reproduction JSON is invalid; independent status cannot be self-asserted.'); return } setBusy(true); try { await client.evidence.reproduce(payload, { projectId }); setMessage('Reproduction custody record submitted; independent verification remains server-reported.'); await load() } catch (error) { const next = problem(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const createDecision = async () => { const payload = json<DecisionAdmissionRequest>(decisionDraft); if (!payload) { setState('hold'); setMessage('Decision JSON is invalid. Provide user-authored constraints and claims linked only to existing receipt IDs.'); return } setBusy(true); try { await client.decisionBriefs.create(payload, { projectId }); await load(); setMessage('Decision brief admitted or held by the durable decision service.') } catch (error) { const next = problem(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  const inspectDecision = async (id: string) => { setBusy(true); try { setSelectedDecision(await client.decisionBriefs.get(id, { projectId })); setState('ready') } catch (error) { const next = problem(error); setState(next.state); setMessage(next.message) } finally { setBusy(false) } }
  if (state === 'loading') return <WorkbenchState kind="loading" title="Recovering durable evidence and decision briefs">Reading verified redacted custody records.</WorkbenchState>
  if (state === 'offline') return <WorkbenchState kind="offline" title="Evidence recovery unavailable" action={<WorkbenchButton onClick={() => void load()}>Retry recovery</WorkbenchButton>}>{message}</WorkbenchState>
  if (state === 'permission') return <SevereFailureBanner title="Project context required" action={<WorkbenchButton onClick={() => void load()}>Retry with project context</WorkbenchButton>}>{message}</SevereFailureBanner>
  return <section className="sa-evidence" aria-labelledby="evidence-heading">
    <SevereFailureBanner title="Integrity is not truth">Custody, hashes, and verification do not establish outcome correctness, independent reproduction, or evidence promotion.</SevereFailureBanner>
    <WorkbenchPanel title={<span id="evidence-heading">Evidence Room</span>} action={<StatusIndicator tone="warning">integrity_not_truth</StatusIndicator>}>
      <p>Artifacts are withheld by the durable API. This interface does not infer their contents, provenance, evidence class, or claim ceiling.</p>
      {message && <p role="status">{message}</p>}
    </WorkbenchPanel>
    {state === 'hold' && <SevereFailureBanner title="Evidence HOLD">{message}</SevereFailureBanner>}
    {state === 'error' && <WorkbenchState kind="error" title="Evidence operation failed" action={<WorkbenchButton onClick={() => void load()}>Reload evidence</WorkbenchButton>}>{message}</WorkbenchState>}
    {state === 'empty' && <WorkbenchState kind="empty" title="No durable evidence or decision briefs">{mode === 'lab' ? 'Derive only from a known persisted execution and request key, or submit canonical JSON for an existing receipt.' : 'Select a completed run to discover its durable evidence. This view never manufactures a receipt, provenance, or result.'}</WorkbenchState>}

    <WorkbenchPanel title="Durable receipt recovery">
      <WorkbenchTable><thead><tr><th scope="col">Receipt</th><th scope="col">Type / class</th><th scope="col">Artifacts</th><th scope="col">Ceiling</th><th scope="col">Inspect</th></tr></thead><tbody>
        {items.map((item, index) => <tr key={item.receipt_id}><td>{mode === 'lab' ? <code>{item.receipt_id}</code> : `Receipt ${index + 1}`}</td><td>{item.evidence_type} / {item.evidence_class}</td><td>{item.artifact_count} withheld</td><td>{item.claim_ceiling}</td><td><WorkbenchButton disabled={busy} onClick={() => void inspect(item.receipt_id)}>Inspect receipt</WorkbenchButton></td></tr>)}
      </tbody></WorkbenchTable>
    </WorkbenchPanel>

    {mode === 'lab' && <>
      <WorkbenchPanel title="Derive from durable execution"><label>Execution ID<input value={executionDraft} onChange={(event) => setExecutionDraft(event.target.value)} autoComplete="off" /></label><label>Request key<input value={requestKey} onChange={(event) => setRequestKey(event.target.value)} autoComplete="off" /></label><WorkbenchButton disabled={busy} onClick={() => void derive()}>Derive evidence receipt</WorkbenchButton></WorkbenchPanel>
      <WorkbenchPanel title="Record existing evidence (Lab JSON)"><label>EvidenceAdmissionRequest JSON<textarea value={recordDraft} onChange={(event) => setRecordDraft(event.target.value)} spellCheck={false} /></label><WorkbenchButton disabled={busy} onClick={() => void record()}>Record canonical receipt</WorkbenchButton></WorkbenchPanel>
      <WorkbenchPanel title="Record reproduction custody (Lab JSON)"><label>ReproductionRequest JSON<textarea value={reproductionDraft} onChange={(event) => setReproductionDraft(event.target.value)} spellCheck={false} /></label><WorkbenchButton disabled={busy} onClick={() => void reproduce()}>Record reproduction</WorkbenchButton></WorkbenchPanel>
    </>}

    {detail && <WorkbenchPanel title={mode === 'lab' ? `Receipt ${detail.receipt_id}` : 'Selected evidence receipt'} action={<StatusIndicator tone="warning">{detail.claim_ceiling}</StatusIndicator>}>
      <dl className="sa-evidence-grid"><div><dt>Type</dt><dd>{detail.evidence_type}</dd></div><div><dt>Class</dt><dd>{detail.evidence_class}</dd></div>{mode === 'lab' && <><div><dt>Receipt hash</dt><dd><code>{detail.receipt_hash}</code></dd></div><div><dt>Manifest hash</dt><dd><code>{detail.manifest_hash}</code></dd></div></>}<div><dt>Artifacts</dt><dd>Withheld ({detail.artifacts.length})</dd></div></dl>
      <WorkbenchButton disabled={busy} onClick={() => void verify()}>Verify receipt afresh</WorkbenchButton>
      {verification && <p role="status">{verification.verified ? 'Verification passed for custody integrity only.' : `Verification failed: ${verification.errors.join('; ')}`}</p>}
      {mode === 'lab' ? <DisclosureRow title="Withheld artifacts">{detail.artifacts.map((artifact) => <p key={artifact.sha256}><code>{artifact.sha256}</code> — {artifact.disposition}: {artifact.reason}</p>)}</DisclosureRow> : <p>Use the verification action to check custody integrity. Hashes and withheld artifact identifiers are available in Lab.</p>}
    </WorkbenchPanel>}

    <WorkbenchPanel title="Evidence maturity from receipt types"><ol className="sa-evidence-ladder">{['fixture', 'local_live', 'reproduction', 'cross_model', 'human_calibration', 'independent_reproduction'].map((step, index) => <li key={step} data-observed={items.some((item) => receiptStep(item.evidence_type) === index + 1)}><strong>{step}</strong> — {items.some((item) => receiptStep(item.evidence_type) === index + 1) ? 'Observed receipt type only.' : 'No receipt type observed.'}</li>)}</ol><p>Later receipt types do not promote earlier evidence. Independent status is unverified unless the server explicitly reports it.</p></WorkbenchPanel>

    <WorkbenchPanel title="Durable decision briefs"><WorkbenchTable><thead><tr><th scope="col">Decision</th><th scope="col">Verdict</th><th scope="col">Claims</th><th scope="col">Inspect</th></tr></thead><tbody>{decisions.map((item, index) => <tr key={item.decision_brief_id}><td>{mode === 'lab' ? <code>{item.decision_brief_id}</code> : `Decision ${index + 1}`}</td><td>{item.verdict}</td><td>{item.claim_count}</td><td><WorkbenchButton disabled={busy} onClick={() => void inspectDecision(item.decision_brief_id)}>Inspect decision</WorkbenchButton></td></tr>)}</tbody></WorkbenchTable>{mode === 'lab' && <><label>DecisionAdmissionRequest JSON<textarea value={decisionDraft} onChange={(event) => setDecisionDraft(event.target.value)} spellCheck={false} /></label><WorkbenchButton disabled={busy} onClick={() => void createDecision()}>Submit user-authored decision</WorkbenchButton></>}</WorkbenchPanel>
    {selectedDecision && <WorkbenchPanel title={mode === 'lab' ? `Decision ${selectedDecision.decision_brief_id}` : 'Selected decision'}><p>Verdict: <strong>{selectedDecision.verdict}</strong> · ceiling: {selectedDecision.claim_ceiling}</p><p>Brief and ledger artifacts are withheld; integrity is not truth.</p>{mode === 'lab' ? <ul>{selectedDecision.claim_refs.map((claim) => <li key={claim.claim_id}>{claim.claim_id}: {claim.receipt_ids.join(', ') || 'No linked receipt IDs'}</li>)}</ul> : <p>{selectedDecision.claim_refs.length} claim link{selectedDecision.claim_refs.length === 1 ? '' : 's'} retained by the durable decision service.</p>}</WorkbenchPanel>}
  </section>
}
