import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'

import { type ArenaV1Client } from '../../journeys/study-design-preflight/types'
import { EvidenceSurface } from './EvidenceSurface'

function client(): ArenaV1Client { return { evidence: { list: vi.fn().mockResolvedValue({ evidence: [{ receipt_id: 'receipt-1', evidence_type: 'fixture', evidence_class: 'fixture', artifact_count: 1, claim_ceiling: 'fixture only' }] }), get: vi.fn().mockResolvedValue({ receipt_id: 'receipt-1', evidence_type: 'fixture', evidence_class: 'fixture', receipt_hash: 'r', manifest_hash: 'm', artifacts: [{ sha256: 'a', disposition: 'withheld', reason: 'redacted' }], claim_ceiling: 'fixture only' }), verify: vi.fn().mockResolvedValue({ receipt_id: 'receipt-1', verified: false, errors: ['hash mismatch'] }), derive: vi.fn().mockResolvedValue({}), record: vi.fn(), reproduce: vi.fn() }, decisionBriefs: { list: vi.fn().mockResolvedValue({ decision_briefs: [] }), get: vi.fn(), create: vi.fn().mockResolvedValue({}) } } as unknown as ArenaV1Client }
describe('EvidenceSurface', () => {
  it('recovers withheld custody detail and reports a fresh verification failure without promotion', async () => { const arena = client(); render(<EvidenceSurface client={arena} mode="guided" />); await screen.findByText('Receipt 1'); expect(screen.queryByText('receipt-1')).not.toBeInTheDocument(); expect(screen.queryByRole('textbox')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Inspect receipt' })); await screen.findByText('Withheld (1)'); fireEvent.click(screen.getByRole('button', { name: 'Verify receipt afresh' })); expect((await screen.findAllByText(/Verification failed: hash mismatch/)).length).toBeGreaterThan(0); expect(screen.getByText(/Integrity is not truth/)).toBeInTheDocument() })
  it('derives only from the exact explicit execution and request key in Lab mode', async () => { const arena = client(); render(<EvidenceSurface client={arena} mode="lab" projectId="project-1" />); await screen.findByText('receipt-1'); const inputs = screen.getAllByRole('textbox'); fireEvent.change(inputs[0], { target: { value: 'execution-1' } }); fireEvent.change(inputs[1], { target: { value: 'request-1' } }); fireEvent.click(screen.getByRole('button', { name: 'Derive evidence receipt' })); await waitFor(() => expect(arena.evidence.derive).toHaveBeenCalledWith({ execution_id: 'execution-1', request_key: 'request-1' }, { projectId: 'project-1' })) })
  it('submits only user-supplied decision JSON with receipt links in Lab mode', async () => { const arena = client(); render(<EvidenceSurface client={arena} mode="lab" projectId="project-1" />); await screen.findByText('receipt-1'); const fields = screen.getAllByRole('textbox'); const decision = { experiment_id: 'experiment-1', execution_id: 'execution-1', risk_constraints: {}, proposed_claims: [{ claim_id: 'c1', statement: 'user authored', kind: 'fixture_observation', linked_receipt_ids: ['receipt-1'] }] }; fireEvent.change(fields.at(-1)!, { target: { value: JSON.stringify(decision) } }); fireEvent.click(screen.getByRole('button', { name: 'Submit user-authored decision' })); await waitFor(() => expect(arena.decisionBriefs.create).toHaveBeenCalledWith(decision, { projectId: 'project-1' })) })
})
